package POJOs;
// Generated Jul 16, 2020, 6:37:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoinghi generated by hbm2java
 */
public class Hoinghi  implements java.io.Serializable {


     private Integer idHoiNghi;
     private Diadiemtochuc diadiemtochuc;
     private String ten;
     private String moTaNgangon;
     private String moTaChitiet;
     private String hinhAnh;
     private Date thoiGian;
     private int soNguoiThamDu;
     private Set memberLists = new HashSet(0);

    public Hoinghi() {
    }

	
    public Hoinghi(Diadiemtochuc diadiemtochuc, String ten, String moTaNgangon, String moTaChitiet, String hinhAnh, Date thoiGian, int soNguoiThamDu) {
        this.diadiemtochuc = diadiemtochuc;
        this.ten = ten;
        this.moTaNgangon = moTaNgangon;
        this.moTaChitiet = moTaChitiet;
        this.hinhAnh = hinhAnh;
        this.thoiGian = thoiGian;
        this.soNguoiThamDu = soNguoiThamDu;
    }
    public Hoinghi(Diadiemtochuc diadiemtochuc, String ten, String moTaNgangon, String moTaChitiet, String hinhAnh, Date thoiGian, int soNguoiThamDu, Set memberLists) {
       this.diadiemtochuc = diadiemtochuc;
       this.ten = ten;
       this.moTaNgangon = moTaNgangon;
       this.moTaChitiet = moTaChitiet;
       this.hinhAnh = hinhAnh;
       this.thoiGian = thoiGian;
       this.soNguoiThamDu = soNguoiThamDu;
       this.memberLists = memberLists;
    }
   
    public Integer getIdHoiNghi() {
        return this.idHoiNghi;
    }
    
    public void setIdHoiNghi(Integer idHoiNghi) {
        this.idHoiNghi = idHoiNghi;
    }
    public Diadiemtochuc getDiadiemtochuc() {
        return this.diadiemtochuc;
    }
    
    public void setDiadiemtochuc(Diadiemtochuc diadiemtochuc) {
        this.diadiemtochuc = diadiemtochuc;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMoTaNgangon() {
        return this.moTaNgangon;
    }
    
    public void setMoTaNgangon(String moTaNgangon) {
        this.moTaNgangon = moTaNgangon;
    }
    public String getMoTaChitiet() {
        return this.moTaChitiet;
    }
    
    public void setMoTaChitiet(String moTaChitiet) {
        this.moTaChitiet = moTaChitiet;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Date getThoiGian() {
        return this.thoiGian;
    }
    
    public void setThoiGian(Date thoiGian) {
        this.thoiGian = thoiGian;
    }
    public int getSoNguoiThamDu() {
        return this.soNguoiThamDu;
    }
    
    public void setSoNguoiThamDu(int soNguoiThamDu) {
        this.soNguoiThamDu = soNguoiThamDu;
    }
    public Set getMemberLists() {
        return this.memberLists;
    }
    
    public void setMemberLists(Set memberLists) {
        this.memberLists = memberLists;
    }




}


