package POJOs;
// Generated Jul 11, 2020, 1:27:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer idMember;
     private String ten;
     private String userName;
     private String password;
     private String email;
     private int vaiTro;
     private Set hoinghis = new HashSet(0);

    public Member() {
    }

	
    public Member(String ten, String userName, String password, String email, int vaiTro) {
        this.ten = ten;
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.vaiTro = vaiTro;
    }
    public Member(String ten, String userName, String password, String email, int vaiTro, Set hoinghis) {
       this.ten = ten;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.vaiTro = vaiTro;
       this.hoinghis = hoinghis;
    }
   
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(int vaiTro) {
        this.vaiTro = vaiTro;
    }
    public Set getHoinghis() {
        return this.hoinghis;
    }
    
    public void setHoinghis(Set hoinghis) {
        this.hoinghis = hoinghis;
    }




}


