package POJOs;
// Generated Jul 16, 2020, 6:37:08 PM by Hibernate Tools 4.3.1



/**
 * MemberListId generated by hbm2java
 */
public class MemberListId  implements java.io.Serializable {


     private int idHoinghi;
     private int idMember;

    public MemberListId() {
    }

    public MemberListId(int idHoinghi, int idMember) {
       this.idHoinghi = idHoinghi;
       this.idMember = idMember;
    }
   
    public int getIdHoinghi() {
        return this.idHoinghi;
    }
    
    public void setIdHoinghi(int idHoinghi) {
        this.idHoinghi = idHoinghi;
    }
    public int getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(int idMember) {
        this.idMember = idMember;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MemberListId) ) return false;
		 MemberListId castOther = ( MemberListId ) other; 
         
		 return (this.getIdHoinghi()==castOther.getIdHoinghi())
 && (this.getIdMember()==castOther.getIdMember());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHoinghi();
         result = 37 * result + this.getIdMember();
         return result;
   }   


}


