package POJOs;
// Generated Jul 16, 2020, 6:37:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer idMember;
     private String ten;
     private String userName;
     private String password;
     private String email;
     private int vaiTro;
     private int active;
     private Set memberLists = new HashSet(0);

    public Member() {
    }

	
    public Member(String ten, String userName, String password, String email, int vaiTro, int active) {
        this.ten = ten;
        this.userName = userName;
        this.password = password;
        this.email = email;
        this.vaiTro = vaiTro;
        this.active = active;
    }
    public Member(String ten, String userName, String password, String email, int vaiTro, int active, Set memberLists) {
       this.ten = ten;
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.vaiTro = vaiTro;
       this.active = active;
       this.memberLists = memberLists;
    }
   
    public Integer getIdMember() {
        return this.idMember;
    }
    
    public void setIdMember(Integer idMember) {
        this.idMember = idMember;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getVaiTro() {
        return this.vaiTro;
    }
    
    public void setVaiTro(int vaiTro) {
        this.vaiTro = vaiTro;
    }
    public int getActive() {
        return this.active;
    }
    
    public void setActive(int active) {
        this.active = active;
    }
    public Set getMemberLists() {
        return this.memberLists;
    }
    
    public void setMemberLists(Set memberLists) {
        this.memberLists = memberLists;
    }




}


