package POJOs;
// Generated Jul 16, 2020, 6:37:08 PM by Hibernate Tools 4.3.1



/**
 * MemberList generated by hbm2java
 */
public class MemberList  implements java.io.Serializable {


     private MemberListId id;
     private Hoinghi hoinghi;
     private Member member;
     private int confirm;

    public MemberList() {
    }

    public MemberList(MemberListId id, Hoinghi hoinghi, Member member, int confirm) {
       this.id = id;
       this.hoinghi = hoinghi;
       this.member = member;
       this.confirm = confirm;
    }
   
    public MemberListId getId() {
        return this.id;
    }
    
    public void setId(MemberListId id) {
        this.id = id;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public int getConfirm() {
        return this.confirm;
    }
    
    public void setConfirm(int confirm) {
        this.confirm = confirm;
    }




}


